model_parameters:

        onnx_model: './garbage.onnx'
        march: "bayes-e"
        layer_out_dump: False
        working_dir: 'model_output'
        output_model_file_prefix: 'horizon_x5'


input_parameters:

        input_name: ""
        input_shape: ''
        input_type_rt: 'nv12'
        input_layout_rt: ''
        input_type_train: 'rgb'
        input_layout_train: 'NCHW'
        norm_type: 'data_scale'
        scale_value: 0.003921568627451


calibration_parameters:


        cal_data_dir: './calib_data'
        cal_data_type: 'float32'
        calibration_type: 'default'


compiler_parameters:
        compile_mode: 'latency'
        debug: False
        optimize_level: 'O3' 











